/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdministrationRouteImport } from './routes/admin.administration'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCommandesRouteImport } from './routes/admin.commandes'
import { Route as AdminCommunicationRouteImport } from './routes/admin.communication'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminDemandesRouteImport } from './routes/admin.demandes'
import { Route as AdminDevisRouteImport } from './routes/admin.devis'
import { Route as AdminDisponibiliteRouteImport } from './routes/admin.disponibilite'
import { Route as AdminFacturesRouteImport } from './routes/admin.factures'
import { Route as AdminPaiementsRouteImport } from './routes/admin.paiements'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as ClientAssistantRouteImport } from './routes/client.assistant'
import { Route as ClientCommandesRouteImport } from './routes/client.commandes'
import { Route as ClientDemandesRouteImport } from './routes/client.demandes'
import { Route as ClientDevisRouteImport } from './routes/client.devis'
import { Route as ClientFacturesRouteImport } from './routes/client.factures'
import { Route as ClientProfilRouteImport } from './routes/client.profil'
import { Route as LoginAdminRouteImport } from './routes/login/admin'
import { Route as LoginClientRouteImport } from './routes/login/client'
import { Route as AdminCatalogueIndexRouteImport } from './routes/admin.catalogue.index'
import { Route as AdminCatalogueIdRouteImport } from './routes/admin.catalogue.$id'
import { Route as AdminClientsIndexRouteImport } from './routes/admin.clients.index'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as AdminProspectsIndexRouteImport } from './routes/admin.prospects.index'
import { Route as AdminProspectsIdRouteImport } from './routes/admin.prospects.$id'
import { Route as ClientCatalogueIndexRouteImport } from './routes/client.catalogue.index'
import { Route as ClientCatalogueIdRouteImport } from './routes/client.catalogue.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdministrationRoute = AdminAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunicationRoute = AdminCommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemandesRoute = AdminDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDevisRoute = AdminDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisponibiliteRoute = AdminDisponibiliteRouteImport.update({
  id: '/disponibilite',
  path: '/disponibilite',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacturesRoute = AdminFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAssistantRoute = ClientAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCommandesRoute = ClientCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDemandesRoute = ClientDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDevisRoute = ClientDevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => ClientRoute,
} as any)
const ClientFacturesRoute = ClientFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfilRoute = ClientProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => ClientRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/login/admin',
  path: '/login/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClientRoute = LoginClientRouteImport.update({
  id: '/login/client',
  path: '/login/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogueIndexRoute = AdminCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueIdRoute = AdminCatalogueIdRouteImport.update({
  id: '/catalogue/$id',
  path: '/catalogue/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProspectsIndexRoute = AdminProspectsIndexRouteImport.update({
  id: '/prospects/',
  path: '/prospects/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProspectsIdRoute = AdminProspectsIdRouteImport.update({
  id: '/prospects/$id',
  path: '/prospects/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ClientCatalogueIndexRoute = ClientCatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => ClientRoute,
} as any)
const ClientCatalogueIdRoute = ClientCatalogueIdRouteImport.update({
  id: '/catalogue/$id',
  path: '/catalogue/$id',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/admin/administration': typeof AdminAdministrationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/disponibilite': typeof AdminDisponibiliteRoute
  '/admin/factures': typeof AdminFacturesRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/commandes': typeof ClientCommandesRoute
  '/client/demandes': typeof ClientDemandesRoute
  '/client/devis': typeof ClientDevisRoute
  '/client/factures': typeof ClientFacturesRoute
  '/client/profil': typeof ClientProfilRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/client': typeof LoginClientRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/catalogue/$id': typeof AdminCatalogueIdRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/prospects/$id': typeof AdminProspectsIdRoute
  '/client/catalogue/$id': typeof ClientCatalogueIdRoute
  '/admin/catalogue/': typeof AdminCatalogueIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/prospects/': typeof AdminProspectsIndexRoute
  '/client/catalogue/': typeof ClientCatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/administration': typeof AdminAdministrationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/disponibilite': typeof AdminDisponibiliteRoute
  '/admin/factures': typeof AdminFacturesRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/commandes': typeof ClientCommandesRoute
  '/client/demandes': typeof ClientDemandesRoute
  '/client/devis': typeof ClientDevisRoute
  '/client/factures': typeof ClientFacturesRoute
  '/client/profil': typeof ClientProfilRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/client': typeof LoginClientRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/catalogue/$id': typeof AdminCatalogueIdRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/prospects/$id': typeof AdminProspectsIdRoute
  '/client/catalogue/$id': typeof ClientCatalogueIdRoute
  '/admin/catalogue': typeof AdminCatalogueIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
  '/admin/prospects': typeof AdminProspectsIndexRoute
  '/client/catalogue': typeof ClientCatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/admin/administration': typeof AdminAdministrationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/commandes': typeof AdminCommandesRoute
  '/admin/communication': typeof AdminCommunicationRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demandes': typeof AdminDemandesRoute
  '/admin/devis': typeof AdminDevisRoute
  '/admin/disponibilite': typeof AdminDisponibiliteRoute
  '/admin/factures': typeof AdminFacturesRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/client/assistant': typeof ClientAssistantRoute
  '/client/commandes': typeof ClientCommandesRoute
  '/client/demandes': typeof ClientDemandesRoute
  '/client/devis': typeof ClientDevisRoute
  '/client/factures': typeof ClientFacturesRoute
  '/client/profil': typeof ClientProfilRoute
  '/login/admin': typeof LoginAdminRoute
  '/login/client': typeof LoginClientRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/catalogue/$id': typeof AdminCatalogueIdRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/admin/prospects/$id': typeof AdminProspectsIdRoute
  '/client/catalogue/$id': typeof ClientCatalogueIdRoute
  '/admin/catalogue/': typeof AdminCatalogueIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
  '/admin/prospects/': typeof AdminProspectsIndexRoute
  '/client/catalogue/': typeof ClientCatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/admin/administration'
    | '/admin/analytics'
    | '/admin/commandes'
    | '/admin/communication'
    | '/admin/conversations'
    | '/admin/demandes'
    | '/admin/devis'
    | '/admin/disponibilite'
    | '/admin/factures'
    | '/admin/paiements'
    | '/client/assistant'
    | '/client/commandes'
    | '/client/demandes'
    | '/client/devis'
    | '/client/factures'
    | '/client/profil'
    | '/login/admin'
    | '/login/client'
    | '/admin/'
    | '/client/'
    | '/admin/catalogue/$id'
    | '/admin/clients/$id'
    | '/admin/prospects/$id'
    | '/client/catalogue/$id'
    | '/admin/catalogue/'
    | '/admin/clients/'
    | '/admin/prospects/'
    | '/client/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/administration'
    | '/admin/analytics'
    | '/admin/commandes'
    | '/admin/communication'
    | '/admin/conversations'
    | '/admin/demandes'
    | '/admin/devis'
    | '/admin/disponibilite'
    | '/admin/factures'
    | '/admin/paiements'
    | '/client/assistant'
    | '/client/commandes'
    | '/client/demandes'
    | '/client/devis'
    | '/client/factures'
    | '/client/profil'
    | '/login/admin'
    | '/login/client'
    | '/admin'
    | '/client'
    | '/admin/catalogue/$id'
    | '/admin/clients/$id'
    | '/admin/prospects/$id'
    | '/client/catalogue/$id'
    | '/admin/catalogue'
    | '/admin/clients'
    | '/admin/prospects'
    | '/client/catalogue'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/admin/administration'
    | '/admin/analytics'
    | '/admin/commandes'
    | '/admin/communication'
    | '/admin/conversations'
    | '/admin/demandes'
    | '/admin/devis'
    | '/admin/disponibilite'
    | '/admin/factures'
    | '/admin/paiements'
    | '/client/assistant'
    | '/client/commandes'
    | '/client/demandes'
    | '/client/devis'
    | '/client/factures'
    | '/client/profil'
    | '/login/admin'
    | '/login/client'
    | '/admin/'
    | '/client/'
    | '/admin/catalogue/$id'
    | '/admin/clients/$id'
    | '/admin/prospects/$id'
    | '/client/catalogue/$id'
    | '/admin/catalogue/'
    | '/admin/clients/'
    | '/admin/prospects/'
    | '/client/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  LoginAdminRoute: typeof LoginAdminRoute
  LoginClientRoute: typeof LoginClientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/administration': {
      id: '/admin/administration'
      path: '/administration'
      fullPath: '/admin/administration'
      preLoaderRoute: typeof AdminAdministrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commandes': {
      id: '/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communication': {
      id: '/admin/communication'
      path: '/communication'
      fullPath: '/admin/communication'
      preLoaderRoute: typeof AdminCommunicationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demandes': {
      id: '/admin/demandes'
      path: '/demandes'
      fullPath: '/admin/demandes'
      preLoaderRoute: typeof AdminDemandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/devis': {
      id: '/admin/devis'
      path: '/devis'
      fullPath: '/admin/devis'
      preLoaderRoute: typeof AdminDevisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disponibilite': {
      id: '/admin/disponibilite'
      path: '/disponibilite'
      fullPath: '/admin/disponibilite'
      preLoaderRoute: typeof AdminDisponibiliteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/factures': {
      id: '/admin/factures'
      path: '/factures'
      fullPath: '/admin/factures'
      preLoaderRoute: typeof AdminFacturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/assistant': {
      id: '/client/assistant'
      path: '/assistant'
      fullPath: '/client/assistant'
      preLoaderRoute: typeof ClientAssistantRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/commandes': {
      id: '/client/commandes'
      path: '/commandes'
      fullPath: '/client/commandes'
      preLoaderRoute: typeof ClientCommandesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/demandes': {
      id: '/client/demandes'
      path: '/demandes'
      fullPath: '/client/demandes'
      preLoaderRoute: typeof ClientDemandesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/devis': {
      id: '/client/devis'
      path: '/devis'
      fullPath: '/client/devis'
      preLoaderRoute: typeof ClientDevisRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/factures': {
      id: '/client/factures'
      path: '/factures'
      fullPath: '/client/factures'
      preLoaderRoute: typeof ClientFacturesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profil': {
      id: '/client/profil'
      path: '/profil'
      fullPath: '/client/profil'
      preLoaderRoute: typeof ClientProfilRouteImport
      parentRoute: typeof ClientRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/login/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/client': {
      id: '/login/client'
      path: '/login/client'
      fullPath: '/login/client'
      preLoaderRoute: typeof LoginClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogue/': {
      id: '/admin/catalogue/'
      path: '/catalogue'
      fullPath: '/admin/catalogue/'
      preLoaderRoute: typeof AdminCatalogueIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogue/$id': {
      id: '/admin/catalogue/$id'
      path: '/catalogue/$id'
      fullPath: '/admin/catalogue/$id'
      preLoaderRoute: typeof AdminCatalogueIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prospects/': {
      id: '/admin/prospects/'
      path: '/prospects'
      fullPath: '/admin/prospects/'
      preLoaderRoute: typeof AdminProspectsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prospects/$id': {
      id: '/admin/prospects/$id'
      path: '/prospects/$id'
      fullPath: '/admin/prospects/$id'
      preLoaderRoute: typeof AdminProspectsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/catalogue/': {
      id: '/client/catalogue/'
      path: '/catalogue'
      fullPath: '/client/catalogue/'
      preLoaderRoute: typeof ClientCatalogueIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/catalogue/$id': {
      id: '/client/catalogue/$id'
      path: '/catalogue/$id'
      fullPath: '/client/catalogue/$id'
      preLoaderRoute: typeof ClientCatalogueIdRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdministrationRoute: typeof AdminAdministrationRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminCommunicationRoute: typeof AdminCommunicationRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminDemandesRoute: typeof AdminDemandesRoute
  AdminDevisRoute: typeof AdminDevisRoute
  AdminDisponibiliteRoute: typeof AdminDisponibiliteRoute
  AdminFacturesRoute: typeof AdminFacturesRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCatalogueIdRoute: typeof AdminCatalogueIdRoute
  AdminClientsIdRoute: typeof AdminClientsIdRoute
  AdminProspectsIdRoute: typeof AdminProspectsIdRoute
  AdminCatalogueIndexRoute: typeof AdminCatalogueIndexRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
  AdminProspectsIndexRoute: typeof AdminProspectsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdministrationRoute: AdminAdministrationRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminCommunicationRoute: AdminCommunicationRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminDemandesRoute: AdminDemandesRoute,
  AdminDevisRoute: AdminDevisRoute,
  AdminDisponibiliteRoute: AdminDisponibiliteRoute,
  AdminFacturesRoute: AdminFacturesRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCatalogueIdRoute: AdminCatalogueIdRoute,
  AdminClientsIdRoute: AdminClientsIdRoute,
  AdminProspectsIdRoute: AdminProspectsIdRoute,
  AdminCatalogueIndexRoute: AdminCatalogueIndexRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
  AdminProspectsIndexRoute: AdminProspectsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientAssistantRoute: typeof ClientAssistantRoute
  ClientCommandesRoute: typeof ClientCommandesRoute
  ClientDemandesRoute: typeof ClientDemandesRoute
  ClientDevisRoute: typeof ClientDevisRoute
  ClientFacturesRoute: typeof ClientFacturesRoute
  ClientProfilRoute: typeof ClientProfilRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientCatalogueIdRoute: typeof ClientCatalogueIdRoute
  ClientCatalogueIndexRoute: typeof ClientCatalogueIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAssistantRoute: ClientAssistantRoute,
  ClientCommandesRoute: ClientCommandesRoute,
  ClientDemandesRoute: ClientDemandesRoute,
  ClientDevisRoute: ClientDevisRoute,
  ClientFacturesRoute: ClientFacturesRoute,
  ClientProfilRoute: ClientProfilRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientCatalogueIdRoute: ClientCatalogueIdRoute,
  ClientCatalogueIndexRoute: ClientCatalogueIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  LoginAdminRoute: LoginAdminRoute,
  LoginClientRoute: LoginClientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
